# Generated by Django 4.1.4 on 2022-12-12 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_cart_id_alter_cart_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="uuid",
            new_name="id",
        ),
    ]
