# Generated by Django 4.1.3 on 2022-11-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(choices=[('', ''), ('EUR', 'EUR'), ('USD', 'USD'), ('CZK', 'CZK')], default='', max_length=3),
        ),
    ]
