# Generated by Django 4.1.4 on 2023-01-02 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0002_alter_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprojectrole",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_users",
                to="workspace.project",
            ),
        ),
        migrations.AlterField(
            model_name="userprojectrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="roles",
                to="workspace.role",
            ),
        ),
        migrations.AlterField(
            model_name="userprojectrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
