# Generated by Django 4.1.4 on 2023-01-02 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0003_alter_userprojectrole_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprojectrole",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="workspace.project",
            ),
        ),
        migrations.AlterField(
            model_name="userprojectrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
