# Generated by Django 4.1.4 on 2023-01-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0006_userproject_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="shortcut_name",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
