# Generated by Django 4.1.4 on 2023-01-02 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0007_alter_currency_shortcut_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="shortcut_name",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="project",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workspace.currency",
            ),
        ),
    ]
