# Generated by Django 4.1.4 on 2023-01-02 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0008_alter_currency_shortcut_name_alter_project_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="currency",
                to="workspace.currency",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="hex_color",
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
