# Generated by Django 4.1.4 on 2023-01-04 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("workspace", "0009_alter_project_currency_alter_project_hex_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproject",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_users",
                to="workspace.project",
            ),
        ),
        migrations.AlterField(
            model_name="userproject",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="userprojects",
                to="workspace.role",
            ),
        ),
        migrations.AlterField(
            model_name="userproject",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_users",
                to="workspace.task",
            ),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
