# Generated by Django 4.1.4 on 2023-01-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0011_remove_role_permissions_alter_role_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
