# Generated by Django 4.1.4 on 2023-01-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0012_alter_project_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproject",
            name="role",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role",
                to="workspace.role",
            ),
        ),
    ]
