# Generated by Django 4.1.4 on 2023-01-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0013_alter_userproject_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproject",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role",
                to="workspace.role",
            ),
        ),
    ]
