# Generated by Django 4.1.5 on 2023-02-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0014_alter_userproject_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='projects',
            field=models.ManyToManyField(through='workspace.UserProject', to='workspace.project'),
        ),
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(through='workspace.UserTask', to='workspace.task'),
        ),
    ]
