# Generated by Django 4.1.5 on 2023-02-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0016_project_status_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DONE', 'done'), ('IN_PROGRESS', 'in progress'), ('ARCHIVED', 'archived'), ('CREATED', 'created')], max_length=36),
        ),
    ]
